### ISSUE TITLE
Incorrect documentation about JWT Authentication

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-pulsar#532]
### Expected Behavior

The YAML example for the JWT Authentication should be
```yaml
pulsar:
  authentication-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpX...
```
with the property `authentication-jwt ` as one field

### Actual Behaviour

Current documentation display `jwt` as a nested field of `authentication`
```yaml
pulsar:
  authentication:
    jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpX...
```

### Steps To Reproduce

Read documentation for [Authentication](https://micronaut-projects.github.io/micronaut-pulsar/2.3.0/guide/#authentication)

### Version

2.3.0
